### ISSUE TITLE
The label(s) kind/cleanup cannot be applied, because the repository doesn't have them.

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kjob#10]
**What happened**:
On create PR everytime we have an error 

```
The label(s) kind/cleanup cannot be applied, because the repository doesn't have them.
```

**What you expected to happen**:
No error happens

**How to reproduce it (as minimally and precisely as possible)**:
Assign label.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kjob version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mimowo** [comment]
/kind cleanup
test

**Comment by mimowo** [comment]
worker, I added this label along with a few others used commonly in Kueue. Let me know if some are still missing
/close

**Comment by mbobrovskyi** [comment]
Thanks!
